# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - deploytest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Set up pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest-8 --activate

      - name: pnpm install, build
        run: |
          pnpm install
          pnpm run build 

      - name: Zip artifact for deployment
        run: |
          cd dist
          sudo apt-get update && sudo apt-get install --yes zip
          zip -r build.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: build.zip
          path: dist/build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: build.zip

      - name: Unzip artifact for deployment
        run: unzip build.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'reactDeploy'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: 'SSH Remote Commands'
        uses: appleboy/ssh-action@v1.0.3
        with:
          script: whoami

